name: Build and Test with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Run tests and upload coverage to SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run:  poetry install
        working-directory: ./justinthecloud

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage xml
          echo "Coverage XML generated at: $(pwd)/coverage.xml"
        working-directory: ./justinthecloud



      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./justinthecloud
          args: >
            -Dsonar.projectKey=justinthecloud
            -Dsonar.organization=iamjustinthecloud
            -Dsonar.python.coverage.reportPaths=coverage.xml